# ABOUTME: Configuration file for chezmoi dotfile manager
# ABOUTME: Sets basic options for dotfile management behavior

[data]
    email = "paulsmith@pobox.com"  # Default email, will be overridden by templates

[edit]
    command = "nvim"  # Use Neovim as the default editor

[git]
    autoAdd = true  # Automatically add changes when using chezmoi edit

[merge]
    command = "nvim"
    args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]

# Use jj for version control instead of git
[cd]
    command = "jj"

# Format settings
format = "yaml"