export PATH="$HOME/.local/bin:$HOME/go/bin:/opt/homebrew/bin:$HOME/.cargo/bin:$PATH"
export HOMEBREW_NO_AUTO_UPDATE=1
[ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc"

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/paul/.lmstudio/bin"
# End of LM Studio CLI section

