[ui]
diff-editor = ":builtin"
default-command = "log"
paginate = "auto"
pager = "less -FRX"
merge-editor = ":builtin"

[git]
write-change-id-header = true

[aliases]
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "closest_nonempty(@)"]

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
'closest_nonempty(to)' = 'heads(::to ~ empty())'
